server:
  port: 3333
  servlet:
    context-path: /api/v1

spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://fashion-people-db.colh2d4vxyrh.ap-northeast-2.rds.amazonaws.com:3306/fashionDB?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: smsw0306
  jpa:
    properties:
      hibernate:
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
